name: Build and test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux dummy crypto
          - OS: ubuntu-latest
            TARGET: x86_64-unknown-linux-gnu
            ADD_INSTALL: |
                sudo apt-get update
                sudo apt-get install -y libudev-dev
            BUILD_OPTIONS: --features crypto_dummy --no-default-features

          # Linux NSS crypto
          - OS: ubuntu-latest
            TARGET: x86_64-unknown-linux-gnu
            ADD_INSTALL: |
                sudo apt-get update
                sudo apt-get install -y libudev-dev mercurial node-gyp ninja-build
            BUILD_OPTIONS: --features crypto_nss --no-default-features

          # Linux openSSL crypto
          - OS: ubuntu-latest
            TARGET: x86_64-unknown-linux-gnu
            ADD_INSTALL: |
                sudo apt-get update
                sudo apt-get install -y libudev-dev openssl
            BUILD_OPTIONS: --features crypto_openssl --no-default-features

          # Mac dummy crypto
          - OS: macos-latest
            TARGET: x86_64-apple-darwin
            BUILD_OPTIONS: --features crypto_dummy --no-default-features --target=x86_64-apple-darwin

          # Windows dummy crypto
          - OS: windows-latest
            TARGET: x86_64-pc-windows-gnu
            BUILD_OPTIONS: --features crypto_dummy --no-default-features --target=x86_64-pc-windows-gnu

    runs-on: ${{ matrix.OS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        run: rustup target add ${{ matrix.TARGET }}

      - name: Install Packages
        if: ${{ matrix.ADD_INSTALL }}
        run: ${{ matrix.ADD_INSTALL }}

      - name: Build
        run: cargo build --all --release ${{ matrix.BUILD_OPTIONS }}

      - name: Test
        run: cargo test ${{ matrix.BUILD_OPTIONS }} -- --show-output
